apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: redis-server
        image: redis:3.2-alpine
